<a href="https://colab.research.google.com/github/Ranjithkumar0203/PyTorchLLM/blob/main/llmPyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [101]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [102]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [103]:
df.shape

(569, 33)

In [104]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [105]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [106]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [107]:
# it standardizes your data so the model can learn properly.
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [108]:
X_train[1]

array([-0.77878317, -0.99060242, -0.76660417, -0.7204463 , -0.446722  ,
       -0.44682454, -0.34270745, -0.66368775, -2.38838507, -0.09705044,
       -0.26203936, -0.22501914, -0.4748766 , -0.38253635,  0.09604541,
        0.66172813,  1.08730629,  0.89549743,  0.13735143,  0.41160153,
       -0.81466567, -1.28240193, -0.84363888, -0.72704468, -0.9190797 ,
       -0.5978061 , -0.51281796, -0.80198118, -1.74126181, -0.53220489])

In [109]:
# This step is about converting your target labels (text) into numbers, because ML models can’t work with strings.
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [110]:
type(y_train)

numpy.ndarray

In [111]:
#Numpy arrays to PyTorch tensors
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [112]:
import torch.nn as nn


class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear1 = nn.Linear(num_features, 30)
    self.relu1 = nn.ReLU()
    self.linear2 = nn.Linear(30, 3)
    self.relu2 = nn.ReLU()
    self.linear3 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear1(features)
    out = self.relu1(out)
    out = self.linear2(out)
    out = self.relu2(out)
    out = self.linear3(out)
    out = self.sigmoid(out)
    return out

In [113]:
learning_rate = 0.1
epochs = 25

In [114]:
# define loss function
loss_function = nn.BCELoss()

In [115]:
X_train_tensor.shape[1]

30

In [116]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1,1))

  # clear gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.7217907309532166
Epoch: 2, Loss: 0.7146306037902832
Epoch: 3, Loss: 0.7078791856765747
Epoch: 4, Loss: 0.7015301585197449
Epoch: 5, Loss: 0.6955093145370483
Epoch: 6, Loss: 0.689875602722168
Epoch: 7, Loss: 0.6844952702522278
Epoch: 8, Loss: 0.6794019341468811
Epoch: 9, Loss: 0.6745664477348328
Epoch: 10, Loss: 0.669844925403595
Epoch: 11, Loss: 0.6651463508605957
Epoch: 12, Loss: 0.66037917137146
Epoch: 13, Loss: 0.6555107235908508
Epoch: 14, Loss: 0.6505313515663147
Epoch: 15, Loss: 0.6454318165779114
Epoch: 16, Loss: 0.6401988863945007
Epoch: 17, Loss: 0.6348013281822205
Epoch: 18, Loss: 0.6292173266410828
Epoch: 19, Loss: 0.6234374046325684
Epoch: 20, Loss: 0.6174411177635193
Epoch: 21, Loss: 0.611225426197052
Epoch: 22, Loss: 0.6047734618186951
Epoch: 23, Loss: 0.5980877876281738
Epoch: 24, Loss: 0.5911760330200195
Epoch: 25, Loss: 0.5840478539466858